buildscript {
    repositories {
        maven { url = 'https://repo.grails.org/grails/restricted' }
    }
    dependencies {
        classpath platform("org.apache.grails:grails-bom:$grailsVersion")
        classpath 'org.apache.grails:grails-gradle-plugins'
        classpath 'cloud.wondrify:asset-pipeline-gradle'
    }
}

version = projectVersion
group = 'io.github.gpc'

apply plugin: 'cloud.wondrify.asset-pipeline'
apply plugin: 'groovy'
apply plugin: 'idea'
apply plugin: 'io.github.gradle-nexus.publish-plugin'
apply plugin: 'maven-publish'
apply plugin: 'org.apache.grails.gradle.grails-plugin'
apply plugin: 'signing'

repositories {
    maven { url = 'https://repo.grails.org/grails/restricted' }
}

dependencies {

    implementation platform("org.apache.grails:grails-bom:$grailsVersion")

    implementation 'org.apache.grails:grails-core'
    implementation 'org.apache.grails:grails-logging'
    implementation 'org.apache.grails:grails-databinding'
    implementation 'org.apache.grails:grails-interceptors'
    implementation 'org.apache.grails:grails-rest-transforms'
    implementation 'org.apache.grails:grails-services'
    implementation 'org.apache.grails:grails-url-mappings'
    implementation 'org.apache.grails:grails-web-boot'
    implementation 'org.apache.grails:grails-async'
    implementation 'org.apache.grails:grails-cache'
    implementation 'org.apache.grails:grails-gsp'
    implementation 'org.apache.grails:grails-data-hibernate5'
    implementation 'org.apache.grails:grails-scaffolding'
    implementation "org.grails.plugins:grails-mail:${grailsMailVersion}"
    implementation "org.apache.grails:grails-quartz:${grailsQuartzVersion}"

    testRuntimeOnly 'com.h2database:h2'
    testRuntimeOnly 'org.apache.tomcat:tomcat-jdbc'

    testImplementation 'org.apache.grails:grails-testing-support-datamapping'
    testImplementation 'org.spockframework:spock-core'
    testImplementation 'org.springframework.boot:spring-boot-starter-tomcat'
}

apply from: layout.projectDirectory.file('gradle/java-config.gradle')
apply from: layout.projectDirectory.file('gradle/plugin-config.gradle')
apply from: layout.projectDirectory.file('gradle/test-config.gradle')
apply from: layout.projectDirectory.file('gradle/publish-config.gradle')
