projectVersion=4.0.1-SNAPSHOT
grailsVersion=6.2.3

# Build script dependency versions
grailsGradlePluginVersion=6.2.4
nexusPublishVersion=2.0.0

# Project dependency versions
javaVersion=11
assetPipelineVersion=4.5.1
grailsMailVersion=4.0.2
grailsQuartzVersion=2.0.13
quartzCoreVersion=2.3.2
spockVersion=2.3-groovy-3.0

# This prevents the Grails Gradle Plugin from unnecessarily excluding slf4j-simple in the generated POMs
# https://github.com/grails/grails-gradle-plugin/issues/222
slf4jPreventExclusion=true

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M