projectVersion=3.0.1-SNAPSHOT
grailsVersion=4.0.13

# Build script dependency versions
grailsGradlePluginVersion=5.3.1
nexusPublishVersion=1.3.0

# Project dependency versions
javaVersion=8
assetPipelineVersion=3.3.4
grailsMailVersion=3.0.0
grailsQuartzVersion=2.0.13
quartzCoreVersion=2.3.2
spockVersion=1.3-groovy-2.5

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M