def versions = new Properties()
file('../gradle.properties').withInputStream {
    versions.load(it)
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.grails.org/grails/restricted' }
}

dependencies {
    implementation platform("org.apache.grails:grails-bom:${versions['grailsVersion']}")
    implementation "org.apache.grails:grails-gradle-plugins"
    implementation "cloud.wondrify:asset-pipeline-grails"
}
