def versions = new Properties()
file('../gradle.properties').withInputStream {
    versions.load(it)
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.grails.org/grails/core' }
}

dependencies {
    implementation "org.grails:grails-gradle-plugin:${versions['grailsGradlePluginVersion']}"
    implementation "io.github.gradle-nexus:publish-plugin:${versions['nexusPublishVersion']}"
    implementation "com.bertramlabs.plugins:asset-pipeline-gradle:${versions['assetPipelineVersion']}"
}