name: "Build"
on:
  push:
    branches:
      - '5.0.x'
  pull_request:
    branches:
      - '5.0.x'
jobs:
  test_project:
    name: "Test Project"
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: liberica
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: "🏃 Run Tests"
        run: ./gradlew check --continue
  build_project:
    name: "Build Project and Publish Snapshot release"
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 8,
          distribution: liberica
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: "🔨 Build Project"
        run: ./gradlew build --continue
      - name: "📤 Publish Snapshot version to Artifactory (repo.grails.org)"
        if: success()
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: ./gradlew publish