name: "Release"
on:
  release:
    types: [ published ]
env:
  GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
  GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
jobs:
  release:
    name: "Release"
    runs-on: ubuntu-24.04
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: liberica
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: "⚙ Run pre-release"
        uses: grails/github-actions/pre-release@main
      - name: "📤 Publish artifacts to Sonatype"
        id: publish_to_sonatype
        env:
          SECRING_FILE: ${{ secrets.SECRING_FILE }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
        run: |
          echo $SECRING_FILE | base64 -d > ${{ github.workspace }}/secring.gpg
          ./gradlew --no-build-cache \
          -Psigning.secretKeyRingFile=${{ github.workspace }}/secring.gpg \
          publishToSonatype \
          closeAndReleaseSonatypeStagingRepository
      - name: "⚙️ Run post-release"
        if: steps.publish_to_sonatype.outcome == 'success'
        uses: grails/github-actions/post-release@main